### ISSUE TITLE
check installation process

### ISSUE THREAD

**Issue by 12rambau** [Louis-Dreyfus-Company/geeservermap#20]
I think I solved the installation process in the latest pre-release. I switch from setuptools to hatch to avoid relying on find_package method for data file discovery. Hatch says everything go in distribution unless discarded which is way more conviient to manage. 

@rodrigo-ldc could you check on your computer if a regular pip install works ?

**Comment by rodrigo-ldc** [comment]
yes! perfect, thanks you @12rambau!
